# Homework 2: Exploratory Data Analysis 
## Part 1: Data Cleaning
#### Abdullah Junejo (07154)
###### aj07154@st.habib.edu.pk

### Initialization

In [2]:
import pandas as pd
import numpy as np

In [3]:
DF = pd.read_csv('loan_small.csv')
DF

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,last_credit_pull_d,application_type
0,1077501,1296599,5000,5000,4975.00000,36 months,10.65,162.87,B,B2,...,5831.78,5000.00,861.07,0.00,0.00,0.00,Jan-15,171.62,Jan-16,INDIVIDUAL
1,1077430,1314167,2500,2500,2500.00000,60 months,15.27,59.83,C,C4,...,1008.71,456.46,435.17,0.00,117.08,1.11,Apr-13,119.66,Sep-13,INDIVIDUAL
2,1077175,1313524,2400,2400,2400.00000,36 months,15.96,84.33,C,C5,...,3003.65,2400.00,603.65,0.00,0.00,0.00,Jun-14,649.91,Jan-16,INDIVIDUAL
3,1076863,1277178,10000,10000,10000.00000,36 months,13.49,339.31,C,C1,...,12226.30,10000.00,2209.33,16.97,0.00,0.00,Jan-15,357.48,Jan-15,INDIVIDUAL
4,1075358,1311748,3000,3000,3000.00000,60 months,12.69,67.79,B,B5,...,3242.17,2233.10,1009.07,0.00,0.00,0.00,Jan-16,67.79,Jan-16,INDIVIDUAL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,1057818,1289186,7000,7000,7000.00000,36 months,8.90,222.28,A,A5,...,8000.34,7000.00,1000.34,0.00,0.00,0.00,Dec-14,229.64,Dec-14,INDIVIDUAL
995,1057629,1289394,2425,2425,2425.00000,36 months,15.27,84.39,C,C4,...,3052.79,2424.99,612.80,15.00,0.00,0.00,Jan-15,16.06,Jul-15,INDIVIDUAL
996,1057621,1289385,6950,6950,6950.00000,36 months,9.91,223.97,B,B1,...,7349.48,6950.01,399.47,0.00,0.00,0.00,Sep-12,1560.92,Apr-14,INDIVIDUAL
997,1057787,1289153,12375,12375,12344.46478,36 months,9.91,398.79,B,B1,...,13399.63,12375.01,1058.95,0.00,0.00,0.00,Dec-12,9056.48,Jan-16,INDIVIDUAL
998,1057770,1289135,35000,35000,33906.19420,60 months,20.30,933.14,E,E5,...,42066.82,24930.60,19834.12,0.00,0.00,0.00,Jan-16,933.14,Jan-16,INDIVIDUAL

### Writing a small block to check for duplicates and remove if they exist or ever exist in future:

In [5]:
#Checking for duplicate rows
if (DF.duplicated().sum()):
    #Remove duplicate rows
    DF = DF.drop_duplicates()
#Checking for duplicate columns
if (DF.columns.duplicated().sum()):
    #Remove duplicate columns
    DF = DF.loc[:, ~DF.columns.duplicated()]
DF

,Id,Member_id,Loan_amnt,Funded_amnt,Funded_amnt_inv,Term,Int_rate,Installment,Grade,Sub_grade,...,Total_pymnt_inv,Total_rec_prncp,Total_rec_int,Total_rec_late_fee,Recoveries,Collection_recovery_fee,Last_pymnt_d,Last_pymnt_amnt,Last_credit_pull_d,Application_type
0,1077501,1296599,5000,5000,4975.00000,36 months,10.65,162.87,B,B2,...,5831.78,5000.00,861.07,0.00,0.00,0.00,Jan-15,171.62,Jan-16,INDIVIDUAL
1,1077430,1314167,2500,2500,2500.00000,60 months,15.27,59.83,C,C4,...,1008.71,456.46,435.17,0.00,117.08,1.11,Apr-13,119.66,Sep-13,INDIVIDUAL
2,1077175,1313524,2400,2400,2400.00000,36 months,15.96,84.33,C,C5,...,3003.65,2400.00,603.65,0.00,0.00,0.00,Jun-14,649.91,Jan-16,INDIVIDUAL
3,1076863,1277178,10000,10000,10000.00000,36 months,13.49,339.31,C,C1,...,12226.30,10000.00,2209.33,16.97,0.00,0.00,Jan-15,357.48,Jan-15,INDIVIDUAL
4,1075358,1311748,3000,3000,3000.00000,60 months,12.69,67.79,B,B5,...,3242.17,2233.10,1009.07,0.00,0.00,0.00,Jan-16,67.79,Jan-16,INDIVIDUAL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,1057818,1289186,7000,7000,7000.00000,36 months,8.90,222.28,A,A5,...,8000.34,7000.00,1000.34,0.00,0.00,0.00,Dec-14,229.64,Dec-14,INDIVIDUAL
995,1057629,1289394,2425,2425,2425.00000,36 months,15.27,84.39,C,C4,...,3052.79,2424.99,612.80,15.00,0.00,0.00,Jan-15,16.06,Jul-15,INDIVIDUAL
996,1057621,1289385,6950,6950,6950.00000,36 months,9.91,223.97,B,B1,...,7349.48,6950.01,399.47,0.00,0.00,0.00,Sep-12,1560.92,Apr-14,INDIVIDUAL
997,1057787,1289153,12375,12375,12344.46478,36 months,9.91,398.79,B,B1,...,13399.63,12375.01,1058.95,0.00,0.00,0.00,Dec-12,9056.48,Jan-16,INDIVIDUAL
998,1057770,1289135,35000,35000,33906.19420,60 months,20.30,933.14,E,E5,...,42066.82,24930.60,19834.12,0.00,0.00,0.00,Jan-16,933.14,Jan-16,INDIVIDUAL

### Capitalizing Columns

In [4]:
DF.columns = [column.capitalize() for column in DF.columns] #Capitalizing Columns
DF

,Id,Member_id,Loan_amnt,Funded_amnt,Funded_amnt_inv,Term,Int_rate,Installment,Grade,Sub_grade,...,Total_pymnt_inv,Total_rec_prncp,Total_rec_int,Total_rec_late_fee,Recoveries,Collection_recovery_fee,Last_pymnt_d,Last_pymnt_amnt,Last_credit_pull_d,Application_type
0,1077501,1296599,5000,5000,4975.00000,36 months,10.65,162.87,B,B2,...,5831.78,5000.00,861.07,0.00,0.00,0.00,Jan-15,171.62,Jan-16,INDIVIDUAL
1,1077430,1314167,2500,2500,2500.00000,60 months,15.27,59.83,C,C4,...,1008.71,456.46,435.17,0.00,117.08,1.11,Apr-13,119.66,Sep-13,INDIVIDUAL
2,1077175,1313524,2400,2400,2400.00000,36 months,15.96,84.33,C,C5,...,3003.65,2400.00,603.65,0.00,0.00,0.00,Jun-14,649.91,Jan-16,INDIVIDUAL
3,1076863,1277178,10000,10000,10000.00000,36 months,13.49,339.31,C,C1,...,12226.30,10000.00,2209.33,16.97,0.00,0.00,Jan-15,357.48,Jan-15,INDIVIDUAL
4,1075358,1311748,3000,3000,3000.00000,60 months,12.69,67.79,B,B5,...,3242.17,2233.10,1009.07,0.00,0.00,0.00,Jan-16,67.79,Jan-16,INDIVIDUAL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,1057818,1289186,7000,7000,7000.00000,36 months,8.90,222.28,A,A5,...,8000.34,7000.00,1000.34,0.00,0.00,0.00,Dec-14,229.64,Dec-14,INDIVIDUAL
995,1057629,1289394,2425,2425,2425.00000,36 months,15.27,84.39,C,C4,...,3052.79,2424.99,612.80,15.00,0.00,0.00,Jan-15,16.06,Jul-15,INDIVIDUAL
996,1057621,1289385,6950,6950,6950.00000,36 months,9.91,223.97,B,B1,...,7349.48,6950.01,399.47,0.00,0.00,0.00,Sep-12,1560.92,Apr-14,INDIVIDUAL
997,1057787,1289153,12375,12375,12344.46478,36 months,9.91,398.79,B,B1,...,13399.63,12375.01,1058.95,0.00,0.00,0.00,Dec-12,9056.48,Jan-16,INDIVIDUAL
998,1057770,1289135,35000,35000,33906.19420,60 months,20.30,933.14,E,E5,...,42066.82,24930.60,19834.12,0.00,0.00,0.00,Jan-16,933.14,Jan-16,INDIVIDUAL

### Converting Relational Data into Numerical/Ordinal Data (Employee Length)

In [14]:
#Closest Reliable/accurate estimate to 10+ Years is 11. That way will not be exagerrating any employee, but we will still might be understating.
#I believe Understating is better than exageratting. < 1 Year is simply 0 as there is no integer less than that.
DF['Emp_length'] = DF['Emp_length'].replace(['10+ years'], '11')
DF['Emp_length'] = DF['Emp_length'].replace(['< 1 year'], '0')
DF['Emp_length'] = DF['Emp_length'].str.extract('(\d+)').astype(int) #Converting Str data into numeric integer data.

In [16]:
DF['Emp_length']

1       0
3      11
4       1
5       3
6       8
       ..
994     5
995     3
996     2
997    11
998    11
Name: Emp_length, Length: 947, dtype: int32

### Changing Loan Status to Binary

In [6]:
#Following the suggestion stated in the quesiton, I decided to keep the answers in binary.
#In otherwords replaced str with bool for saving space.
DF['Loan_status'] = DF['Loan_status'].replace(['Fully Paid'], True) #Considered Good Status
DF['Loan_status'] = DF['Loan_status'].replace(['Charged Off'], False) #Considered Bad as Google States: "A charge-off means a lender or creditor has written the account off as a loss, and the account is closed to future charges. "
DF['Loan_status'] = DF['Loan_status'].replace(['Current'], True) #Considered Good, Making Payments on Time.
DF['Loan_status'] = DF['Loan_status'].replace(['Default'], False) #Considered Bad Naturally
DF['Loan_status'] = DF['Loan_status'].replace(['Late (31-120 days)'], False) #Considered Bad Naturally (2)
DF['Loan_status']

0       True
1      False
2       True
3       True
4       True
       ...
994     True
995     True
996     True
997     True
998     True
Name: Loan_status, Length: 999, dtype: bool

### Correcting Label 'Months'

In [7]:
DF['Term'] = DF['Term'].str.replace('months', '') #Excluding 'month' from entries so that data becomes numerical
DF['Term'] = DF['Term'].astype(int) #Setting int type

In [8]:
DF=DF.rename(columns={'Term' : 'Term_(Months)'})
DF

,Id,Member_id,Loan_amnt,Funded_amnt,Funded_amnt_inv,Term_(Months),Int_rate,Installment,Grade,Sub_grade,...,Total_pymnt_inv,Total_rec_prncp,Total_rec_int,Total_rec_late_fee,Recoveries,Collection_recovery_fee,Last_pymnt_d,Last_pymnt_amnt,Last_credit_pull_d,Application_type
0,1077501,1296599,5000,5000,4975.00000,36,10.65,162.87,B,B2,...,5831.78,5000.00,861.07,0.00,0.00,0.00,Jan-15,171.62,Jan-16,INDIVIDUAL
1,1077430,1314167,2500,2500,2500.00000,60,15.27,59.83,C,C4,...,1008.71,456.46,435.17,0.00,117.08,1.11,Apr-13,119.66,Sep-13,INDIVIDUAL
2,1077175,1313524,2400,2400,2400.00000,36,15.96,84.33,C,C5,...,3003.65,2400.00,603.65,0.00,0.00,0.00,Jun-14,649.91,Jan-16,INDIVIDUAL
3,1076863,1277178,10000,10000,10000.00000,36,13.49,339.31,C,C1,...,12226.30,10000.00,2209.33,16.97,0.00,0.00,Jan-15,357.48,Jan-15,INDIVIDUAL
4,1075358,1311748,3000,3000,3000.00000,60,12.69,67.79,B,B5,...,3242.17,2233.10,1009.07,0.00,0.00,0.00,Jan-16,67.79,Jan-16,INDIVIDUAL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,1057818,1289186,7000,7000,7000.00000,36,8.90,222.28,A,A5,...,8000.34,7000.00,1000.34,0.00,0.00,0.00,Dec-14,229.64,Dec-14,INDIVIDUAL
995,1057629,1289394,2425,2425,2425.00000,36,15.27,84.39,C,C4,...,3052.79,2424.99,612.80,15.00,0.00,0.00,Jan-15,16.06,Jul-15,INDIVIDUAL
996,1057621,1289385,6950,6950,6950.00000,36,9.91,223.97,B,B1,...,7349.48,6950.01,399.47,0.00,0.00,0.00,Sep-12,1560.92,Apr-14,INDIVIDUAL
997,1057787,1289153,12375,12375,12344.46478,36,9.91,398.79,B,B1,...,13399.63,12375.01,1058.95,0.00,0.00,0.00,Dec-12,9056.48,Jan-16,INDIVIDUAL
998,1057770,1289135,35000,35000,33906.19420,60,20.30,933.14,E,E5,...,42066.82,24930.60,19834.12,0.00,0.00,0.00,Jan-16,933.14,Jan-16,INDIVIDUAL

### Dealing with Null Values:

In [9]:
DF.isnull().sum()

Id                           0
Member_id                    0
Loan_amnt                    0
Funded_amnt                  0
Funded_amnt_inv              0
Term_(Months)                0
Int_rate                     0
Installment                  0
Grade                        0
Sub_grade                    0
Emp_title                   51
Emp_length                  17
Home_ownership               0
Annual_inc                   0
Verification_status          0
Issue_d                      0
Loan_status                  0
Pymnt_plan                   0
Purpose                      0
Title                        0
Zip_code                     0
Addr_state                   0
Dti                          0
Delinq_2yrs                  0
Earliest_cr_line             0
Inq_last_6mths               0
Mths_since_last_delinq     774
Mths_since_last_record     979
Open_acc                     0
Pub_rec                      0
Revol_bal                    0
Revol_util                   0
Total_acc                    0
Initial_list_status          0
Out_prncp                    0
Out_prncp_inv                0
Total_pymnt                  0
Total_pymnt_inv              0
Total_rec_prncp              0
Total_rec_int                0
Total_rec_late_fee           0
Recoveries                   0
Collection_recovery_fee      0
Last_pymnt_d                 1
Last_pymnt_amnt              0
Last_credit_pull_d           0
Application_type             0
dtype: int64

In [10]:
#Remove rows with null in the following columns: Employee Title, Employee length, and Last_payment_d
#It is not accurate to fill in Employee Title, Length with a mode/median Their absence does not signify a zero point value. We will be making a bold assumption if we do so. Therefore, these should be dropped as they are anomalies in our dataframe. w 
DF = DF.dropna(subset=['Emp_title', 'Emp_length', 'Last_pymnt_d'])
#The Reason I chose to drop Last Payment D is it only had one null entry, so i decided to look closely into it.
#Turns out it had many irregularities/anamolies/zero in many entries. That very row this means was some sort of dummy/perhaps test data. Therefore, it should be remove as it does not make any sense at all.
DF.isnull().sum()

Id                           0
Member_id                    0
Loan_amnt                    0
Funded_amnt                  0
Funded_amnt_inv              0
Term_(Months)                0
Int_rate                     0
Installment                  0
Grade                        0
Sub_grade                    0
Emp_title                    0
Emp_length                   0
Home_ownership               0
Annual_inc                   0
Verification_status          0
Issue_d                      0
Loan_status                  0
Pymnt_plan                   0
Purpose                      0
Title                        0
Zip_code                     0
Addr_state                   0
Dti                          0
Delinq_2yrs                  0
Earliest_cr_line             0
Inq_last_6mths               0
Mths_since_last_delinq     735
Mths_since_last_record     928
Open_acc                     0
Pub_rec                      0
Revol_bal                    0
Revol_util                   0
Total_acc                    0
Initial_list_status          0
Out_prncp                    0
Out_prncp_inv                0
Total_pymnt                  0
Total_pymnt_inv              0
Total_rec_prncp              0
Total_rec_int                0
Total_rec_late_fee           0
Recoveries                   0
Collection_recovery_fee      0
Last_pymnt_d                 0
Last_pymnt_amnt              0
Last_credit_pull_d           0
Application_type             0
dtype: int64

In [11]:
#droping the Mths_since_last_delinq and Mths_since_last_record coloumns as most of the values are null.
#This means that since most accountss have never gone into delinquincy
#Most accounts don't have last record
#We can't extrapolate/fill in with mode/median values for the sake of accuracy/relliability of our data.

DF = DF.drop(['Mths_since_last_delinq', 'Mths_since_last_record'], axis=1)
DF.isnull().sum()

Id                         0
Member_id                  0
Loan_amnt                  0
Funded_amnt                0
Funded_amnt_inv            0
Term_(Months)              0
Int_rate                   0
Installment                0
Grade                      0
Sub_grade                  0
Emp_title                  0
Emp_length                 0
Home_ownership             0
Annual_inc                 0
Verification_status        0
Issue_d                    0
Loan_status                0
Pymnt_plan                 0
Purpose                    0
Title                      0
Zip_code                   0
Addr_state                 0
Dti                        0
Delinq_2yrs                0
Earliest_cr_line           0
Inq_last_6mths             0
Open_acc                   0
Pub_rec                    0
Revol_bal                  0
Revol_util                 0
Total_acc                  0
Initial_list_status        0
Out_prncp                  0
Out_prncp_inv              0
Total_pymnt                0
Total_pymnt_inv            0
Total_rec_prncp            0
Total_rec_int              0
Total_rec_late_fee         0
Recoveries                 0
Collection_recovery_fee    0
Last_pymnt_d               0
Last_pymnt_amnt            0
Last_credit_pull_d         0
Application_type           0
dtype: int64

### No Null Values Remain

## Generating .CSV File

In [18]:
#Convert to .CSV file

DF.to_csv('loan_small_Cleaned.csv', index=False)