# HW 2: Data Wrangling 
#### Abdullah Junejo aj07154@st.habib.edu.pk

### Q1

In [4]:
import pandas as pd
import numpy as np #Importing relavent libraries
DataF = pd.read_csv('580SurveyCleanup.csv') #Importing .csv file and creating a DataFrame Data Structure.
DataF.head() #View top entries to get general idea of the data conditions.

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Q11.1,Q11.2,Q11.3,Q11.4,Q12,Q12.1,Q12.2,Q12.3,Q12.4,Q13
0,No.,Time,Status,Duration (Seconds),Access Code,Email Address,IP Address,Country,Region,City / Town / District,...,Some familiarity,Average user,Frequent use for projects,Fluent/expert,Little/none,Some familiarity,Average user,Frequent use for projects,Fluent/expert,What is your goal for learning about data anal...
1,1,10/3/20 5:49 PM,Completed,11646,NaN,NaN,100.36.167.226,United States,Virginia,Fairfax,...,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN
2,2,10/3/20 5:49 PM,Completed,113,NaN,NaN,98.169.26.134,United States,Virginia,Fairfax,...,NaN,1,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
3,3,10/3/20 5:49 PM,Completed,572,NaN,NaN,98.169.52.23,United States,Virginia,Greenway Downs,...,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,"As part of my work, I have access to a lot of ..."
4,4,10/3/20 5:50 PM,Completed,365,NaN,NaN,69.255.182.253,United States,Virginia,Gainesville,...,NaN,NaN,1,NaN,NaN,1,NaN,NaN,NaN,NaN

In [5]:
DataF.columns = DataF.iloc[0,:] #Setting First Row as Column Names.
DataF = DataF[1:] #Removing First Row
DataF.head()

,No.,Time,Status,Duration (Seconds),Access Code,Email Address,IP Address,Country,Region,City / Town / District,...,Some familiarity,Average user,Frequent use for projects,Fluent/expert,Little/none,Some familiarity,Average user,Frequent use for projects,Fluent/expert,What is your goal for learning about data analytics?
1,1,10/3/20 5:49 PM,Completed,11646,NaN,NaN,100.36.167.226,United States,Virginia,Fairfax,...,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN
2,2,10/3/20 5:49 PM,Completed,113,NaN,NaN,98.169.26.134,United States,Virginia,Fairfax,...,NaN,1,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
3,3,10/3/20 5:49 PM,Completed,572,NaN,NaN,98.169.52.23,United States,Virginia,Greenway Downs,...,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,"As part of my work, I have access to a lot of ..."
4,4,10/3/20 5:50 PM,Completed,365,NaN,NaN,69.255.182.253,United States,Virginia,Gainesville,...,NaN,NaN,1,NaN,NaN,1,NaN,NaN,NaN,NaN
5,5,10/3/20 5:51 PM,Completed,92,NaN,NaN,138.88.108.230,United States,NaN,NaN,...,1,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,Learn

In [6]:
DataF.reset_index(drop=True, inplace=True) #Reseting INdex
DataF = DataF.iloc[:,1:12] #Select All  Rows, Ignore zeroth column (which simply was for indexing purposes in data and is getting redundant) upto 12th (Not including questions)
DataF.head()

,Time,Status,Duration (Seconds),Access Code,Email Address,IP Address,Country,Region,City / Town / District,Latitude,Longitude
0,10/3/20 5:49 PM,Completed,11646,NaN,NaN,100.36.167.226,United States,Virginia,Fairfax,-77.2891,38.8209
1,10/3/20 5:49 PM,Completed,113,NaN,NaN,98.169.26.134,United States,Virginia,Fairfax,-77.263,38.8605
2,10/3/20 5:49 PM,Completed,572,NaN,NaN,98.169.52.23,United States,Virginia,Greenway Downs,-77.2331,38.9645
3,10/3/20 5:50 PM,Completed,365,NaN,NaN,69.255.182.253,United States,Virginia,Gainesville,-77.6308,38.8175
4,10/3/20 5:51 PM,Completed,92,NaN,NaN,138.88.108.230,United States,NaN,NaN,-97.822,37.751

#### Just realized that columns 12 onwards had their titles in different row. So importing .csv file into another dataframe variable.

In [7]:
Questions = pd.read_csv('580SurveyCleanup.csv')
Questions = Questions.iloc[:,[12,13]] #Selecting Question 1
Questions.head()

    Q1  Q1.1
0  2.0   4.0
1  NaN   1.0
2  1.0   NaN
3  1.0   NaN
4  1.0   NaN

In [8]:
Questions.columns = Questions.iloc[0].astype(str) 
Questions = Questions[1:]
Questions.head()

0  2.0  4.0
1  NaN  1.0
2  1.0  NaN
3  1.0  NaN
4  1.0  NaN
5  1.0  NaN

In [10]:
def Populate(DataFramee,column_lst):
    DataFramee = DataFramee.fillna('') #Removing NAN Values
    for column in column_lst:
        DataFramee[column] = DataFramee[column].replace(1.0, column) #Replacing 1.0 with column name
    return DataFramee
def Merge(DataFramee, column_lst, New_Name):
    DataFramee[New_Name] = '' #Initializing a new column
    for column in column_lst:
        DataFramee[New_Name] += DataFramee[column] #Adding Columns
    DataFramee.drop(columns=column_lst, inplace=True) #Dropping Old Columns
    return DataFramee
Questions=Populate(Questions,['2.0','4.0']) 
Questions #Test

0   2.0  4.0
1        4.0
2   2.0
3   2.0
4   2.0
5   2.0
6   2.0
7   2.0
8   2.0
9   2.0
10       4.0
11  2.0
12       4.0
13  2.0
14  2.0
15       4.0
16       4.0
17  2.0
18  2.0
19       4.0
20       4.0
21       4.0
22  2.0
23       4.0
24       4.0
25       4.0
26  2.0
27  2.0
28       4.0
29       4.0
30  2.0
31       4.0
32  2.0
33  2.0
34       4.0
35  2.0
36       4.0

In [11]:
Questions=Merge(Questions,['2.0','4.0'],'Question 1')
Questions.head

<bound method NDFrame.head of 0  Question 1
1         4.0
2         2.0
3         2.0
4         2.0
5         2.0
6         2.0
7         2.0
8         2.0
9         2.0
10        4.0
11        2.0
12        4.0
13        2.0
14        2.0
15        4.0
16        4.0
17        2.0
18        2.0
19        4.0
20        4.0
21        4.0
22        2.0
23        4.0
24        4.0
25        4.0
26        2.0
27        2.0
28        4.0
29        4.0
30        2.0
31        4.0
32        2.0
33        2.0
34        4.0
35        2.0
36        4.0>

In [12]:
Questions.reset_index(drop=True, inplace=True) #Reseting Index
Questions

0  Question 1
0         4.0
1         2.0
2         2.0
3         2.0
4         2.0
5         2.0
6         2.0
7         2.0
8         2.0
9         4.0
10        2.0
11        4.0
12        2.0
13        2.0
14        4.0
15        4.0
16        2.0
17        2.0
18        4.0
19        4.0
20        4.0
21        2.0
22        4.0
23        4.0
24        4.0
25        2.0
26        2.0
27        4.0
28        4.0
29        2.0
30        4.0
31        2.0
32        2.0
33        4.0
34        2.0
35        4.0

#### Looks like we will have to tailor every question individually and then merge everything in the end.

In [17]:
Questions2 = pd.read_csv('580SurveyCleanup.csv')
Questions2 = Questions2.iloc[:, [14, 15, 16, 17]]
Questions2.columns = Questions2.iloc[0].astype(str)
Questions2 = Questions2[1:]
Questions2

0  Male Female NonBinary Prefer not to answer
1   NaN      1       NaN                  NaN
2   NaN      1       NaN                  NaN
3     1    NaN       NaN                  NaN
4   NaN    NaN       NaN                    1
5     1    NaN       NaN                  NaN
6   NaN      1       NaN                  NaN
7   NaN    NaN         1                  NaN
8   NaN      1       NaN                  NaN
9     1    NaN       NaN                  NaN
10    1    NaN       NaN                  NaN
11  NaN      1       NaN                  NaN
12  NaN      1       NaN                  NaN
13    1    NaN       NaN                  NaN
14  NaN      1       NaN                  NaN
15  NaN      1       NaN                  NaN
16    1    NaN       NaN                  NaN
17    1    NaN       NaN                  NaN
18    1    NaN       NaN                  NaN
19    1    NaN       NaN                  NaN
20  NaN      1       NaN                  NaN
21    1    NaN       NaN                  NaN
22  NaN      1       NaN                  NaN
23  NaN      1       NaN                  NaN
24    1    NaN       NaN                  NaN
25  NaN      1       NaN                  NaN
26    1    NaN       NaN                  NaN
27    1    NaN       NaN                  NaN
28    1    NaN       NaN                  NaN
29  NaN      1       NaN                  NaN
30    1    NaN       NaN                  NaN
31  NaN      1       NaN                  NaN
32  NaN      1       NaN                  NaN
33    1    NaN       NaN                  NaN
34    1    NaN       NaN                  NaN
35    1    NaN       NaN                  NaN
36  NaN      1       NaN                  NaN

In [18]:
def Populate_v2(DataFramee,column_lst,replacement_value): #Modifying Populate
    DataFramee = DataFramee.fillna('') #Removing NAN Values
    for column in column_lst:
        DataFramee[column] = DataFramee[column].replace(replacement_value, column) #Replacing 1 with column name
    return DataFramee
        
Questions2=Populate_v2(Questions2, ['Male', 'Female', 'NonBinary', 'Prefer not to answer'],'1') #Passing a list manually containing column names
Questions2

0   Male  Female  NonBinary  Prefer not to answer
1         Female
2         Female
3   Male
4                            Prefer not to answer
5   Male
6         Female
7                 NonBinary
8         Female
9   Male
10  Male
11        Female
12        Female
13  Male
14        Female
15        Female
16  Male
17  Male
18  Male
19  Male
20        Female
21  Male
22        Female
23        Female
24  Male
25        Female
26  Male
27  Male
28  Male
29        Female
30  Male
31        Female
32        Female
33  Male
34  Male
35  Male
36        Female

In [19]:
Questions2 = Merge(Questions2,['Male', 'Female', 'NonBinary', 'Prefer not to answer'],'Question 2')
Questions2.reset_index(drop=True, inplace=True) #Reseting Index
Questions2

0             Question 2
0                 Female
1                 Female
2                   Male
3   Prefer not to answer
4                   Male
5                 Female
6              NonBinary
7                 Female
8                   Male
9                   Male
10                Female
11                Female
12                  Male
13                Female
14                Female
15                  Male
16                  Male
17                  Male
18                  Male
19                Female
20                  Male
21                Female
22                Female
23                  Male
24                Female
25                  Male
26                  Male
27                  Male
28                Female
29                  Male
30                Female
31                Female
32                  Male
33                  Male
34                  Male
35                Female

#### Testing Merge Function on Question 8 of Survey

In [26]:
Questions8 = pd.read_csv('580SurveyCleanup.csv')
Questions8 = Questions8.iloc[:,[23,24,25,26]]
Questions8.columns = Questions8.iloc[0].astype(str)
Questions8 = Questions8[1:]
Questions8

0  Microsoft/Windows Apple/MacBook Other           nan
1                NaN             1   NaN           NaN
2                NaN             1   NaN           NaN
3                NaN             1   NaN           NaN
4                  1           NaN   NaN           NaN
5                NaN             2   NaN           NaN
6                NaN           NaN   NaN           NaN
7                  1           NaN   NaN           NaN
8                NaN           NaN   NaN           NaN
9                  1           NaN   NaN           NaN
10               NaN           NaN   NaN           NaN
11                 1           NaN   NaN           NaN
12                 1           NaN   NaN           NaN
13               NaN             1   NaN           NaN
14                 1           NaN   NaN           NaN
15                 1           NaN   NaN           NaN
16                 1           NaN   NaN           NaN
17                 1             1   NaN           NaN
18                 1           NaN   NaN           NaN
19                 1           NaN   NaN           NaN
20               NaN             1   NaN           NaN
21                 1           NaN   NaN           NaN
22                 1           NaN   NaN           NaN
23                 1             1   NaN           NaN
24                 1           NaN   NaN           NaN
25                 1           NaN   NaN           NaN
26                 0           NaN   NaN           NaN
27               NaN             1   NaN           NaN
28                 1           NaN   NaN           NaN
29                 1           NaN   NaN           NaN
30               NaN             1   NaN           NaN
31                 1           NaN   NaN           NaN
32                 1             1   NaN           NaN
33                 1           NaN   NaN           NaN
34                 1           NaN   NaN           NaN
35                 1           NaN   NaN           NaN
36               NaN           NaN     1  Acer/Windows

In [27]:
Questions8=Populate_v2(Questions8,['Microsoft/Windows', 'Apple/MacBook','Other','nan'],['0','1','2'])

In [28]:
Questions8=Merge(Questions8,['Microsoft/Windows', 'Apple/MacBook','Other','nan'],'Question 8')
Questions8.reset_index(drop=True, inplace=True) #Reseting Index
Questions8

0                       Question 8
0                    Apple/MacBook
1                    Apple/MacBook
2                    Apple/MacBook
3                Microsoft/Windows
4                    Apple/MacBook
5
6                Microsoft/Windows
7
8                Microsoft/Windows
9
10               Microsoft/Windows
11               Microsoft/Windows
12                   Apple/MacBook
13               Microsoft/Windows
14               Microsoft/Windows
15               Microsoft/Windows
16  Microsoft/WindowsApple/MacBook
17               Microsoft/Windows
18               Microsoft/Windows
19                   Apple/MacBook
20               Microsoft/Windows
21               Microsoft/Windows
22  Microsoft/WindowsApple/MacBook
23               Microsoft/Windows
24               Microsoft/Windows
25               Microsoft/Windows
26                   Apple/MacBook
27               Microsoft/Windows
28               Microsoft/Windows
29                   Apple/MacBook
30               Microsoft/Windows
31  Microsoft/WindowsApple/MacBook
32               Microsoft/Windows
33               Microsoft/Windows
34               Microsoft/Windows
35               OtherAcer/Windows

#### Using Same Method for Question 9

In [30]:
Questions9 = pd.read_csv('580SurveyCleanup.csv')
Questions9 = Questions9.iloc[:,[27,28,29]]
Questions9.columns = Questions9.iloc[0].astype(str)
Questions9 = Questions9[1:]
Questions9=Populate_v2(Questions9,['Yes, Full Time', 'Working, but not Full Time','Not Working while attending Mason'],'1')
Questions9=Merge(Questions9,['Yes, Full Time', 'Working, but not Full Time','Not Working while attending Mason'],'Question 9')
Questions9.reset_index(drop=True, inplace=True) #Reseting Index
Questions9

0                          Question 9
0   Not Working while attending Mason
1          Working, but not Full Time
2                      Yes, Full Time
3   Not Working while attending Mason
4                      Yes, Full Time
5
6          Working, but not Full Time
7
8                      Yes, Full Time
9
10  Not Working while attending Mason
11  Not Working while attending Mason
12         Working, but not Full Time
13  Not Working while attending Mason
14  Not Working while attending Mason
15  Not Working while attending Mason
16                     Yes, Full Time
17  Not Working while attending Mason
18  Not Working while attending Mason
19         Working, but not Full Time
20                     Yes, Full Time
21  Not Working while attending Mason
22         Working, but not Full Time
23  Not Working while attending Mason
24                     Yes, Full Time
25                     Yes, Full Time
26  Not Working while attending Mason
27  Not Working while attending Mason
28  Not Working while attending Mason
29  Not Working while attending Mason
30                     Yes, Full Time
31  Not Working while attending Mason
32                     Yes, Full Time
33                     Yes, Full Time
34  Not Working while attending Mason
35                     Yes, Full Time

#### Questions 10-12 are exactly same, so copy pasting the same code but creating different dataframes.

In [31]:
Questions10 = pd.read_csv('580SurveyCleanup.csv')
Questions10 = Questions10.iloc[:,[30,31,32,33,34]]
Questions10.columns = Questions10.iloc[0].astype(str)
Questions10 = Questions10[1:]

Questions10=Populate_v2(Questions10,['Little/none', 'Some familiarity','Average user','Frequent use for projects' , 'Fluent/expert'],'1')
Questions10=Merge(Questions10,['Little/none','Some familiarity','Average user','Frequent use for projects','Fluent/expert'],'Question 10')
Questions10.reset_index(drop=True, inplace=True) #Reseting Index
Questions10

0                 Question 10
0            Some familiarity
1                Average user
2            Some familiarity
3                Average user
4            Some familiarity
5
6                Average user
7
8            Some familiarity
9
10                Little/none
11  Frequent use for projects
12           Some familiarity
13               Average user
14               Average user
15           Some familiarity
16               Average user
17  Frequent use for projects
18                Little/none
19           Some familiarity
20           Some familiarity
21           Some familiarity
22           Some familiarity
23                Little/none
24               Average user
25               Average user
26               Average user
27               Average user
28               Average user
29               Average user
30                Little/none
31               Average user
32               Average user
33               Average user
34           Some familiarity
35           Some familiarity

In [32]:
Questions11 = pd.read_csv('580SurveyCleanup.csv')
Questions11 = Questions11.iloc[:,[35,36,37,38,39]]
Questions11.columns = Questions11.iloc[0].astype(str)
Questions11 = Questions11[1:]

Questions11=Populate_v2(Questions11,['Little/none', 'Some familiarity','Average user','Frequent use for projects' , 'Fluent/expert'],'1')
Questions11=Merge(Questions11,['Little/none','Some familiarity','Average user','Frequent use for projects','Fluent/expert'],'Question 11')
Questions11.reset_index(drop=True, inplace=True) #Reseting Index
Questions11

0                 Question 11
0                 Little/none
1                Average user
2                 Little/none
3   Frequent use for projects
4            Some familiarity
5
6                Average user
7
8   Frequent use for projects
9
10                Little/none
11               Average user
12               Average user
13               Average user
14                Little/none
15           Some familiarity
16           Some familiarity
17  Frequent use for projects
18                Little/none
19              Fluent/expert
20           Some familiarity
21                Little/none
22  Frequent use for projects
23                Little/none
24               Average user
25           Some familiarity
26  Frequent use for projects
27  Frequent use for projects
28               Average user
29               Average user
30           Some familiarity
31  Frequent use for projects
32           Some familiarity
33               Average user
34           Some familiarity
35                Little/none

In [60]:
Data = pd.read_csv('580SurveyCleanup.csv')
Questions12 = Data.iloc[:,[40,41,42,43,44]]
Questions13 = Data.iloc[:,[45]]
Questions13 = Questions13[1:].fillna('')
Questions13.columns=['Question 13']
Questions12.columns = Questions12.iloc[0].astype(str)
Questions12 = Questions12[1:]

Questions12=Populate_v2(Questions12,['Little/none', 'Some familiarity','Average user','Frequent use for projects' , 'Fluent/expert'],'1')
Questions12=Merge(Questions12,['Little/none','Some familiarity','Average user','Frequent use for projects','Fluent/expert'],'Question 12')
Questions12.reset_index(drop=True, inplace=True) #Reseting Index
Questions13.reset_index(drop=True, inplace=True) #Reseting Index
Questions8to13=pd.concat([Questions8,Questions9,Questions10,Questions11,Questions12,Questions13],axis=1)
Questions8to13

,Question 8,Question 9,Question 10,Question 11,Question 12,Question 13
0,Apple/MacBook,Not Working while attending Mason,Some familiarity,Little/none,Some familiarity,
1,Apple/MacBook,"Working, but not Full Time",Average user,Average user,Little/none,
2,Apple/MacBook,"Yes, Full Time",Some familiarity,Little/none,Average user,"As part of my work, I have access to a lot of ..."
3,Microsoft/Windows,Not Working while attending Mason,Average user,Frequent use for projects,Some familiarity,
4,Apple/MacBook,"Yes, Full Time",Some familiarity,Some familiarity,Average user,Learn
5,,,,,,
6,Microsoft/Windows,"Working, but not Full Time",Average user,Average user,Average user,To deduce meaningful interpretation for Financ...
7,,,,,,
8,Microsoft/Windows,"Yes, Full Time",Some familiarity,Frequent use for projects,Average user,
9,,,,,,
10,Microsoft/Windows,Not Working while attending Mason,Little/none,Little/none,Some familiarity,To see if it is a field I am interested in pur...
11,Microsoft/Windows,Not Working while attending Mason,Frequent use for projects,Average user,Frequent use for projects,To learn and explore cutting edge data technol...
12,Apple/MacBook,"Working, but not Full Time",Some familiarity,Average user,Average user,Learn to select the appropriate tools to condu...
13,Microsoft/Windows,Not Working while attending Mason,Average user,Average user,Average user,
14,Microsoft/Windows,Not Working while attending Mason,Average user,Little/none,Little/none,improve my skills
15,Microsoft/Windows,Not Working while attending Mason,Some familiarity,Some familiarity,Some familiarity,My professional goal is to become a Financial ...
16,Microsoft/WindowsApple/MacBook,"Yes, Full Time",Average user,Some familiarity,Some familiarity,able to compliment my Computational Social Sci...
17,Microsoft/Windows,Not Working while attending Mason,Frequent use for projects,Frequent use for projects,Average user,To start a company
18,Microsoft/Windows,Not Working while attending Mason,Little/none,Little/none,Average user,To be able understand and manipulate data to m...
19,Apple/MacBook,"Working, but not Full Time",Some familiarity,Fluent/expert,Average user,My ultimate goal is to get a job as a sports a...
20,Microsoft/Windows,"Yes, Full Time",Some familiarity,Some familiarity,Some familiarity,To understand how to properly interpret and di...
21,Microsoft/Windows,Not Working while attending Mason,Some familiarity,Little/none,Average user,"After graduating data analytics, I want myself..."
22,Microsoft/WindowsApple/MacBook,"Working, but not Full Time",Some familiarity,Frequent use for projects,Little/none,Learning how to appropriately handle large qua...
23,Microsoft/Windows,Not Working while attending Mason,Little/none,Little/none,Little/none,To learn and understand the fundamentals and m...
24,Microsoft/Windows,"Yes, Full Time",Average user,Average user,Average user,The goal is to learn as many programming/stati...
25,Microsoft/Windows,"Yes, Full Time",Average user,Some familiarity,Some familiarity,Learning analytics tool and being good at them
26,Apple/MacBook,Not Working while attending Mason,Average user,Frequent use for projects,Average user,I want to be as a data analyst
27,Microsoft/Windows,Not Working while attending Mason,Average user,Frequent use for projects,Average user,It is very relevant to my PhD research area an...
28,Microsoft/Windows,Not Working while attending Mason,Average user,Average user,Average user,Learn how to handle large amount structured an...
29,Apple/MacBook,Not Working while attending Mason,Average user,Average user,Frequent use for projects,To become a good Data Analyst and work for top...
30,Microsoft/Windows,"Yes, Full Time",Little/none,Some familiarity,Some familiarity,Get a better understanding of the granularity ...
31,Microsoft/WindowsApple/MacBook,Not Working while attending Mason,Average user,Frequent use for projects,Frequent use for projects,
32,Microsoft/Windows,"Yes, Full Time",Average user,Some familiarity,Some familiarity,Learn how data analytics works
33,Microsoft/Windows,"Yes, Full Time",Average user,Average user,Average user,Advance my career in data science
34,Microsoft/Windows,Not Working while attending Mason,Some familiarity,Some familiarity,Some familiarity,Getting a good job
35,OtherAcer/Windows,"Yes, Full Time",Some familiarity,Little/none,Little/none,to use the skills at work.

#### Merging DataFrames

In [61]:
Questions3to7 = Data.iloc[:,[18,19,20,21,22]]
Questions3to7 = Questions3to7[1:]
NewColumnNames=['Question 3','Question 4','Question 5','Question 6','Question 7'] #Mistakenly Renamed them differently before, so doing thiss again for consistency
Questions3to7.columns=NewColumnNames
Questions3to7.reset_index(drop=True, inplace=True) #Reseting Index
FinalDataFrame=pd.concat([DataF,Questions,Questions2,Questions3to7,Questions8to13],axis=1)
FinalDataFrame.to_csv('formatted_580SurveyCleanup.csv', index=False) #Exporting Files
FinalDataFrame

,Time,Status,Duration (Seconds),Access Code,Email Address,IP Address,Country,Region,City / Town / District,Latitude,...,Question 4,Question 5,Question 6,Question 7,Question 8,Question 9,Question 10,Question 11,Question 12,Question 13
0,10/3/20 5:49 PM,Completed,11646,NaN,NaN,100.36.167.226,United States,Virginia,Fairfax,-77.2891,...,63,Taiwan,economics,2021-12-31,Apple/MacBook,Not Working while attending Mason,Some familiarity,Little/none,Some familiarity,
1,10/3/20 5:49 PM,Completed,113,NaN,NaN,98.169.26.134,United States,Virginia,Fairfax,-77.263,...,59,India,Finance,2021-05-01,Apple/MacBook,"Working, but not Full Time",Average user,Average user,Little/none,
2,10/3/20 5:49 PM,Completed,572,NaN,NaN,98.169.52.23,United States,Virginia,Greenway Downs,-77.2331,...,70,India,Computer Applications,2022-06-01,Apple/MacBook,"Yes, Full Time",Some familiarity,Little/none,Average user,"As part of my work, I have access to a lot of ..."
3,10/3/20 5:50 PM,Completed,365,NaN,NaN,69.255.182.253,United States,Virginia,Gainesville,-77.6308,...,66,South Korea,Business Management,2021-12-31,Microsoft/Windows,Not Working while attending Mason,Average user,Frequent use for projects,Some familiarity,
4,10/3/20 5:51 PM,Completed,92,NaN,NaN,138.88.108.230,United States,NaN,NaN,-97.822,...,70,US,Yes,2021-01-01,Apple/MacBook,"Yes, Full Time",Some familiarity,Some familiarity,Average user,Learn
5,10/3/20 5:59 PM,Incomplete,221,NaN,NaN,108.56.134.80,United States,Virginia,Reston,-77.3489,...,NaN,NaN,NaN,NaN,,,,,,
6,10/3/20 6:23 PM,Completed,115983,NaN,NaN,108.48.175.220,United States,Virginia,Arlington,-77.0987,...,70,pakistan,Finance,2022-07-15,Microsoft/Windows,"Working, but not Full Time",Average user,Average user,Average user,To deduce meaningful interpretation for Financ...
7,10/3/20 7:10 PM,Incomplete,40,NaN,NaN,173.67.199.85,United States,Virginia,Ashburn,-77.539,...,5.2,NaN,NaN,NaN,,,,,,
8,10/3/20 7:25 PM,Completed,137,NaN,NaN,74.96.114.12,United States,Virginia,Woodbridge,-77.3197,...,71,china,Economic,2021-12-15,Microsoft/Windows,"Yes, Full Time",Some familiarity,Frequent use for projects,Average user,
9,10/3/20 7:56 PM,Incomplete,179,NaN,NaN,107.77.241.32,United States,Texas,NaN,-96.8217,...,71,Uzbekistan,Economics with Finance,NaN,,,,,,
10,10/3/20 8:14 PM,Completed,127,NaN,NaN,138.88.182.245,United States,Maryland,Takoma Park,-77.004,...,66,USA,BIT,2022-05-01,Microsoft/Windows,Not Working while attending Mason,Little/none,Little/none,Some familiarity,To see if it is a field I am interested in pur...
11,10/3/20 9:38 PM,Completed,269,NaN,NaN,72.83.246.60,United States,Virginia,Fairfax,-77.263,...,66,India,Computer Engineering,2021-05-31,Microsoft/Windows,Not Working while attending Mason,Frequent use for projects,Average user,Frequent use for projects,To learn and explore cutting edge data technol...
12,10/3/20 9:41 PM,Completed,117,NaN,NaN,96.241.43.105,United States,Virginia,Chantilly,-77.4512,...,69,Romania,Biology,2021-08-26,Apple/MacBook,"Working, but not Full Time",Some familiarity,Average user,Average user,Learn to select the appropriate tools to condu...
13,10/3/20 10:49 PM,Completed,5966,NaN,NaN,71.191.72.223,United States,Virginia,Burke,-77.2866,...,66,India,Cse,2021-12-25,Microsoft/Windows,Not Working while attending Mason,Average user,Average user,Average user,
14,10/3/20 11:25 PM,Completed,254,NaN,NaN,73.134.53.227,United States,Maryland,Hyattsville,-76.8696,...,67,China,Management,2021-12-31,Microsoft/Windows,Not Working while attending Mason,Average user,Little/none,Little/none,improve my skills
15,10/4/20 12:28 AM,Completed,526,NaN,NaN,73.86.219.52,United States,Maryland,Baltimore,-76.6355,...,72,Uzbekistan,Economics with Finance,2022-05-01,Microsoft/Windows,Not Working while attending Mason,Some familiarity,Some familiarity,Some familiarity,My professional goal is to become a Financial ...
16,10/4/20 5:22 AM,Completed,398,NaN,NaN,69.138.215.127,United States,Virginia,Arlington,-77.113,...,68,USA,Economics,2022-05-31,Microsoft/WindowsApple/MacBook,"Yes, Full Time",Average user,Some familiarity,Some familiarity,able to compliment my Computational Social Sci...
17,10/4/20 5:36 AM,Completed,128253,NaN,NaN,72.196.231.70,United States,Virginia,Springfield,-77.2333,...,60,India,Engineering,2021-01-12,Microsoft/Windows,Not Working while attending Mason,Frequent use for projects,Frequent use for projects,Average user,To start a company
18,10/4/20 5:47 AM,Completed,239,NaN,NaN,100.15.54.17,United States,Virginia,Woodbridge,-77.3197,...,67,Ethiopia,Accounting and ISOM,2021-12-20,Microsoft/Windows,Not Working while attending Mason,Little/none,Little/none,Average user,To be able understand and manipulate data to m...
19,10/4/20 10:32 AM,Completed,255,NaN,NaN,184.170.83.239,United States,Virginia,Rustburg,-79.0985,...,67,United States,Statistics,2021-12-20,Apple/MacBook,"Working, but not Full Time",Some familiarity,Fluent/expert,Average user,My ultimate goal is to get a job as a sports a...
20,10/4/20 11:03 AM,Completed,256,NaN,NaN,100.36.243.102,United States,Virginia,Fairfax,-77.3375,...,74,United States,Computer Science,2022-05-01,Microsoft/Windows,"Yes, Full Time",Some familiarity,Some familiarity,Some familiarity,To understand how to properly interpret and di...
21,10/4/20 12:34 PM,Completed,674,NaN,NaN,108.56.134.80,United States,Virginia,Reston,-77.3489,...,65,India,Computer science,2022-04-16,Microsoft/Windows,Not Working while attending Mason,Some familiarity,Little/none,Average user,"After graduating data analytics, I want myself..."
22,10/4/20 1:36 PM,Completed,130,NaN,NaN,73.163.163.82,United States,Maryland,Baltimore,-76.557,...,67,USA,Mathematics & Statistics,2021-12-18,Microsoft/WindowsApple/MacBook,"Working, but not Full Time",Some familiarity,Frequent use for projects,Little/none,Learning how to appropriately handle large qua...
23,10/4/20 1:50 PM,Completed,275,NaN,NaN,138.88.223.87,United States,NaN,NaN,-97.822,...,75,Nigeria,Economics,2021-05-14,Microsoft/Windows,Not Working while attending Mason,Little/none,Little/none,Little/none,To learn and understand the fundamentals and m...
24,10/4/20 9:28 PM,Completed,325,NaN,NaN,100.36.50.114,United States,NaN,NaN,-97.822,...,67,USA,Systems Engineering,2022-12-19,Microsoft/Windows,"Yes, Full Time",Average user,Average user,Average user,The goal is to learn as many programming/stati...
25,10/5/20 9:37 AM,Completed,257,NaN,NaN,108.51.59.195,United States,Virginia,Burke,-77.2866,...,68,Taiwan,Civil engineering,2021-05-30,Microsoft/Windows,"Yes, Full Time",Average user,Some familiarity,Some familiarity,Learning analytics tool and being good at them
26,10/5/20 9:36 AM,Completed,657,NaN,NaN,72.83.246.219,United States,Virginia,Fairfax,-77.263,...,72,India,ECE,2021-12-11,Apple/MacBook,Not Working while attending Mason,Average user,Frequent use for projects,Average user,I want to be as a data analyst
27,10/5/20 10:36 AM,Completed,1750,NaN,NaN,100.36.118.186,United States,Virginia,Burke,-77.2866,...,6l,Nigeria,Quantity Surveying,2023-05-24,Microsoft/Windows,Not Working while attending Mason,Average user,Frequent use for projects,Average user,It is very relevant to my PhD research area an...
28,10/5/20 11:02 AM,Completed,887,NaN,NaN,172.58.187.98,United States,Maryland,Baltimore,-76.6949,...,64,India,Bachelor of Engineering,2021-12-30,Microsoft/Windows,Not Working while attending Mason,Average user,Average user,Average user,Learn how to handle large amount structured an...
29,10/5/20 11:17 AM,Completed,180,NaN,NaN,72.196.230.201,United States,Virginia,Springfield,-77.2333,...,71,India,B.Tech in CS,2021-12-15,Apple/MacBook,Not Working while attending Mason,Average user,Average user,Frequent use for projects,To become a good Data Analyst and work for top...
30,10/5/20 12:52 PM,Completed,392,NaN,NaN,108.18.111.204,United States,Virginia,Lorton,-77.206,...,56,United States,BS accounting,2021-05-01,Microsoft/Windows,"Yes, Full Time",Little/none,Some familiarity,Some familiarity,Get a better understanding of the granularity ...
31,10/5/20 12:56 PM,Incomplete,192,NaN,NaN,71.191.72.223,United States,Virginia,Burke,-77.2866,...,70,India,Bachelor of engineering,2021-12-21,Microsoft/WindowsApple/MacBook,Not Working while attending Mason,Average user,Frequent use for projects,Frequent use for projects,
32,10/5/20 1:52 PM,Completed,277,NaN,NaN,184.191.72.8,United States,Virginia,Falls Church,-77.1425,...,7O,United States ; Pakistan,Criminology Law and Soci,2021-12-18,Microsoft/Windows,"Yes, Full Time",Average user,Some familiarity,Some familiarity,Learn how data analytics works
33,10/5/20 3:34 PM,Completed,119,NaN,NaN,141.156.160.243,United States,NaN,NaN,-97.822,...,73,USA,Economics,2022-05-15,Microsoft/Windows,"Yes, Full Time",Average user,Average user,Average user,Advance my career in data science
34,10/5/20 3:41 PM,Completed,149,NaN,NaN,71.206.51.121,United States,Maryland,Frederick,-77.2758,...,68,Vietnam,Finance,2022-12-12,Microsoft/Windows,Not Working while attending Mason,Some familiarity,Some familiarity,Some familiarity,Getting a good job
35,10/5/20 5:58 PM,Completed,285,NaN,NaN,129.174.252.234,United States,Virginia,Fairfax,-77.3375,...,66,Uzbekistan,Psychology,2021-12-20,OtherAcer/Windows,"Yes, Full Time",Some familiarity,Little/none,Little/none,to use the skills at work.

## Q2

In [38]:
import pandas as pd
import numpy as np
DataFrame1 = pd.read_csv('formatted_580SurveyCleanup.csv')
DataFrame1.isnull().sum()

Time                       0
Status                     0
Duration (Seconds)         0
Access Code               36
Email Address             36
IP Address                 0
Country                    0
Region                     4
City / Town / District     5
Latitude                   0
Longitude                  0
Question 1                 0
Question 2                 0
Question 3                 0
Question 4                 1
Question 5                 2
Question 6                 2
Question 7                 3
Question 8                 3
Question 9                 3
Question 10                3
Question 11                3
Question 12                3
Question 13                9
dtype: int64

##### Here we can see clearly that Access Code and and Email address is null in its entirety. Dropping it is wise as it is taking up useful space. (Assuming the original survey did not had this mandatory, we can drop it without any severe consequences).

In [39]:
DataFrame1 = DataFrame1.drop(['Access Code', 'Email Address'], axis=1)
DataFrame1

,Time,Status,Duration (Seconds),IP Address,Country,Region,City / Town / District,Latitude,Longitude,Question 1,...,Question 4,Question 5,Question 6,Question 7,Question 8,Question 9,Question 10,Question 11,Question 12,Question 13
0,10/3/20 5:49 PM,Completed,11646,100.36.167.226,United States,Virginia,Fairfax,-77.2891,38.8209,4.0,...,63,Taiwan,economics,2021-12-31,Apple/MacBook,Not Working while attending Mason,Some familiarity,Little/none,Some familiarity,NaN
1,10/3/20 5:49 PM,Completed,113,98.169.26.134,United States,Virginia,Fairfax,-77.2630,38.8605,2.0,...,59,India,Finance,2021-05-01,Apple/MacBook,"Working, but not Full Time",Average user,Average user,Little/none,NaN
2,10/3/20 5:49 PM,Completed,572,98.169.52.23,United States,Virginia,Greenway Downs,-77.2331,38.9645,2.0,...,70,India,Computer Applications,2022-06-01,Apple/MacBook,"Yes, Full Time",Some familiarity,Little/none,Average user,"As part of my work, I have access to a lot of ..."
3,10/3/20 5:50 PM,Completed,365,69.255.182.253,United States,Virginia,Gainesville,-77.6308,38.8175,2.0,...,66,South Korea,Business Management,2021-12-31,Microsoft/Windows,Not Working while attending Mason,Average user,Frequent use for projects,Some familiarity,NaN
4,10/3/20 5:51 PM,Completed,92,138.88.108.230,United States,NaN,NaN,-97.8220,37.7510,2.0,...,70,US,Yes,2021-01-01,Apple/MacBook,"Yes, Full Time",Some familiarity,Some familiarity,Average user,Learn
5,10/3/20 5:59 PM,Incomplete,221,108.56.134.80,United States,Virginia,Reston,-77.3489,38.9311,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,10/3/20 6:23 PM,Completed,115983,108.48.175.220,United States,Virginia,Arlington,-77.0987,38.8600,2.0,...,70,pakistan,Finance,2022-07-15,Microsoft/Windows,"Working, but not Full Time",Average user,Average user,Average user,To deduce meaningful interpretation for Financ...
7,10/3/20 7:10 PM,Incomplete,40,173.67.199.85,United States,Virginia,Ashburn,-77.5390,39.0180,2.0,...,5.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,10/3/20 7:25 PM,Completed,137,74.96.114.12,United States,Virginia,Woodbridge,-77.3197,38.6780,2.0,...,71,china,Economic,2021-12-15,Microsoft/Windows,"Yes, Full Time",Some familiarity,Frequent use for projects,Average user,NaN
9,10/3/20 7:56 PM,Incomplete,179,107.77.241.32,United States,Texas,NaN,-96.8217,32.7787,4.0,...,71,Uzbekistan,Economics with Finance,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,10/3/20 8:14 PM,Completed,127,138.88.182.245,United States,Maryland,Takoma Park,-77.0040,38.9827,2.0,...,66,USA,BIT,2022-05-01,Microsoft/Windows,Not Working while attending Mason,Little/none,Little/none,Some familiarity,To see if it is a field I am interested in pur...
11,10/3/20 9:38 PM,Completed,269,72.83.246.60,United States,Virginia,Fairfax,-77.2630,38.8605,4.0,...,66,India,Computer Engineering,2021-05-31,Microsoft/Windows,Not Working while attending Mason,Frequent use for projects,Average user,Frequent use for projects,To learn and explore cutting edge data technol...
12,10/3/20 9:41 PM,Completed,117,96.241.43.105,United States,Virginia,Chantilly,-77.4512,38.9036,2.0,...,69,Romania,Biology,2021-08-26,Apple/MacBook,"Working, but not Full Time",Some familiarity,Average user,Average user,Learn to select the appropriate tools to condu...
13,10/3/20 10:49 PM,Completed,5966,71.191.72.223,United States,Virginia,Burke,-77.2866,38.7851,2.0,...,66,India,Cse,2021-12-25,Microsoft/Windows,Not Working while attending Mason,Average user,Average user,Average user,NaN
14,10/3/20 11:25 PM,Completed,254,73.134.53.227,United States,Maryland,Hyattsville,-76.8696,38.9544,4.0,...,67,China,Management,2021-12-31,Microsoft/Windows,Not Working while attending Mason,Average user,Little/none,Little/none,improve my skills
15,10/4/20 12:28 AM,Completed,526,73.86.219.52,United States,Maryland,Baltimore,-76.6355,39.3555,4.0,...,72,Uzbekistan,Economics with Finance,2022-05-01,Microsoft/Windows,Not Working while attending Mason,Some familiarity,Some familiarity,Some familiarity,My professional goal is to become a Financial ...
16,10/4/20 5:22 AM,Completed,398,69.138.215.127,United States,Virginia,Arlington,-77.1130,38.8747,2.0,...,68,USA,Economics,2022-05-31,Microsoft/WindowsApple/MacBook,"Yes, Full Time",Average user,Some familiarity,Some familiarity,able to compliment my Computational Social Sci...
17,10/4/20 5:36 AM,Completed,128253,72.196.231.70,United States,Virginia,Springfield,-77.2333,38.7438,2.0,...,60,India,Engineering,2021-01-12,Microsoft/Windows,Not Working while attending Mason,Frequent use for projects,Frequent use for projects,Average user,To start a company
18,10/4/20 5:47 AM,Completed,239,100.15.54.17,United States,Virginia,Woodbridge,-77.3197,38.6780,4.0,...,67,Ethiopia,Accounting and ISOM,2021-12-20,Microsoft/Windows,Not Working while attending Mason,Little/none,Little/none,Average user,To be able understand and manipulate data to m...
19,10/4/20 10:32 AM,Completed,255,184.170.83.239,United States,Virginia,Rustburg,-79.0985,37.2544,4.0,...,67,United States,Statistics,2021-12-20,Apple/MacBook,"Working, but not Full Time",Some familiarity,Fluent/expert,Average user,My ultimate goal is to get a job as a sports a...
20,10/4/20 11:03 AM,Completed,256,100.36.243.102,United States,Virginia,Fairfax,-77.3375,38.8357,4.0,...,74,United States,Computer Science,2022-05-01,Microsoft/Windows,"Yes, Full Time",Some familiarity,Some familiarity,Some familiarity,To understand how to properly interpret and di...
21,10/4/20 12:34 PM,Completed,674,108.56.134.80,United States,Virginia,Reston,-77.3489,38.9311,2.0,...,65,India,Computer science,2022-04-16,Microsoft/Windows,Not Working while attending Mason,Some familiarity,Little/none,Average user,"After graduating data analytics, I want myself..."
22,10/4/20 1:36 PM,Completed,130,73.163.163.82,United States,Maryland,Baltimore,-76.5570,39.2784,4.0,...,67,USA,Mathematics & Statistics,2021-12-18,Microsoft/WindowsApple/MacBook,"Working, but not Full Time",Some familiarity,Frequent use for projects,Little/none,Learning how to appropriately handle large qua...
23,10/4/20 1:50 PM,Completed,275,138.88.223.87,United States,NaN,NaN,-97.8220,37.7510,4.0,...,75,Nigeria,Economics,2021-05-14,Microsoft/Windows,Not Working while attending Mason,Little/none,Little/none,Little/none,To learn and understand the fundamentals and m...
24,10/4/20 9:28 PM,Completed,325,100.36.50.114,United States,NaN,NaN,-97.8220,37.7510,4.0,...,67,USA,Systems Engineering,2022-12-19,Microsoft/Windows,"Yes, Full Time",Average user,Average user,Average user,The goal is to learn as many programming/stati...
25,10/5/20 9:37 AM,Completed,257,108.51.59.195,United States,Virginia,Burke,-77.2866,38.7851,2.0,...,68,Taiwan,Civil engineering,2021-05-30,Microsoft/Windows,"Yes, Full Time",Average user,Some familiarity,Some familiarity,Learning analytics tool and being good at them
26,10/5/20 9:36 AM,Completed,657,72.83.246.219,United States,Virginia,Fairfax,-77.2630,38.8605,2.0,...,72,India,ECE,2021-12-11,Apple/MacBook,Not Working while attending Mason,Average user,Frequent use for projects,Average user,I want to be as a data analyst
27,10/5/20 10:36 AM,Completed,1750,100.36.118.186,United States,Virginia,Burke,-77.2866,38.7851,4.0,...,6l,Nigeria,Quantity Surveying,2023-05-24,Microsoft/Windows,Not Working while attending Mason,Average user,Frequent use for projects,Average user,It is very relevant to my PhD research area an...
28,10/5/20 11:02 AM,Completed,887,172.58.187.98,United States,Maryland,Baltimore,-76.6949,39.2820,4.0,...,64,India,Bachelor of Engineering,2021-12-30,Microsoft/Windows,Not Working while attending Mason,Average user,Average user,Average user,Learn how to handle large amount structured an...
29,10/5/20 11:17 AM,Completed,180,72.196.230.201,United States,Virginia,Springfield,-77.2333,38.7438,2.0,...,71,India,B.Tech in CS,2021-12-15,Apple/MacBook,Not Working while attending Mason,Average user,Average user,Frequent use for projects,To become a good Data Analyst and work for top...
30,10/5/20 12:52 PM,Completed,392,108.18.111.204,United States,Virginia,Lorton,-77.2060,38.6911,4.0,...,56,United States,BS accounting,2021-05-01,Microsoft/Windows,"Yes, Full Time",Little/none,Some familiarity,Some familiarity,Get a better understanding of the granularity ...
31,10/5/20 12:56 PM,Incomplete,192,71.191.72.223,United States,Virginia,Burke,-77.2866,38.7851,2.0,...,70,India,Bachelor of engineering,2021-12-21,Microsoft/WindowsApple/MacBook,Not Working while attending Mason,Average user,Frequent use for projects,Frequent use for projects,NaN
32,10/5/20 1:52 PM,Completed,277,184.191.72.8,United States,Virginia,Falls Church,-77.1425,38.8472,2.0,...,7O,United States ; Pakistan,Criminology Law and Soci,2021-12-18,Microsoft/Windows,"Yes, Full Time",Average user,Some familiarity,Some familiarity,Learn how data analytics works
33,10/5/20 3:34 PM,Completed,119,141.156.160.243,United States,NaN,NaN,-97.8220,37.7510,4.0,...,73,USA,Economics,2022-05-15,Microsoft/Windows,"Yes, Full Time",Average user,Average user,Average user,Advance my career in data science
34,10/5/20 3:41 PM,Completed,149,71.206.51.121,United States,Maryland,Frederick,-77.2758,39.4624,2.0,...,68,Vietnam,Finance,2022-12-12,Microsoft/Windows,Not Working while attending Mason,Some familiarity,Some familiarity,Some familiarity,Getting a good job
35,10/5/20 5:58 PM,Completed,285,129.174.252.234,United States,Virginia,Fairfax,-77.3375,38.8357,4.0,...,66,Uzbekistan,Psychology,2021-12-20,OtherAcer/Windows,"Yes, Full Time",Some familiarity,Little/none,Little/none,to use the skills at work.

In [40]:
#from geopy import Nominatim
#def get_region_from_coordinates(latitude, longitude):
#    geolocator = Nominatim(user_agent="geoapiExercises")
#    location = geolocator.reverse(f"{latitude}, {longitude}", exactly_one=True)
    
#    if location is not None:
#        return location.address
#    else:
#        return "Region not found"
#region=get_region_from_coordinates(-97, 37)
#print(region)

#Tried using Geopy Library to Suggest region based on longitude and Laititude readings but ran into some issues.
#Therefore replacing it with couldn't calculate
DataFrame1['Region'].fillna('Calculation Failed',inplace=True)
DataFrame1['City / Town / District'].fillna('Calculation Failed',inplace=True)
#Fixing Some Anamolies:
DataFrame1['Question 3'].replace('1993', '27', inplace=True)
DataFrame1['Question 3'].replace('2 3', '23', inplace=True)
#These all clearly look like typos
DataFrame1['Question 4'].replace('5.2', '52', inplace=True)
DataFrame1['Question 4'].replace('7O', '70', inplace=True)
DataFrame1['Question 4'].replace('6l', '61', inplace=True)

#Filling in missing height values by first converting to numeric and then calculating mean and then going back to string.
DataFrame1['Question 4'] = pd.to_numeric(DataFrame1['Question 4'])
DataFrame1['Question 4'].fillna(DataFrame1['Question 4'].mean(), inplace=True)
DataFrame1['Question 4'] = DataFrame1['Question 4'].astype(int).astype(str)
DataFrame1.isnull().sum()

Time                      0
Status                    0
Duration (Seconds)        0
IP Address                0
Country                   0
Region                    0
City / Town / District    0
Latitude                  0
Longitude                 0
Question 1                0
Question 2                0
Question 3                0
Question 4                0
Question 5                2
Question 6                2
Question 7                3
Question 8                3
Question 9                3
Question 10               3
Question 11               3
Question 12               3
Question 13               9
dtype: int64

In [41]:
DataFrame1['Question 5'] = DataFrame1['Question 5'].str.capitalize() #Capitalizing all strings
DataFrame1['Question 5'] = DataFrame1['Question 5'].replace(['Usa', 'United states', 'United states ', 'Us'], 'USA') #Deciding on a Unified spelling for USA
DataFrame1['Question 5'] = DataFrame1['Question 5'].replace(['United States ; Pakistan '], 'USA ; Pakistan') #Capitalising the instance with both USA and Pakistan
DataFrame1['Question 5'].fillna(DataFrame1['Question 5'].mode()[0], inplace=True) #Filling Mode value inplace of empty space
DataFrame1.isnull().sum()

Time                      0
Status                    0
Duration (Seconds)        0
IP Address                0
Country                   0
Region                    0
City / Town / District    0
Latitude                  0
Longitude                 0
Question 1                0
Question 2                0
Question 3                0
Question 4                0
Question 5                0
Question 6                2
Question 7                3
Question 8                3
Question 9                3
Question 10               3
Question 11               3
Question 12               3
Question 13               9
dtype: int64

In [42]:
DataFrame1['Question 6'] = DataFrame1['Question 6'].str.capitalize() #Capitalizing and deciding on a single common name for various entities
DataFrame1['Question 6'] = DataFrame1['Question 6'].replace('Yes', 'Unrecognized  Degree') #Just a self-made assumption
DataFrame1['Question 6'] = DataFrame1['Question 6'].replace('Economic', 'Economics')
DataFrame1['Question 6'] = DataFrame1['Question 6'].replace(['Cse', 'Computer science engineering ', 'Computer engineering'], 'Computer Science and Engineering')
DataFrame1['Question 6'] = DataFrame1['Question 6'].replace(['Bachelor of engineering ', 'Engineering ','Ece'], 'Bachelor of Engineering')
DataFrame1['Question 6'] = DataFrame1['Question 6'].replace('Criminology law and soci', 'Criminology Law and Sociology')
DataFrame1['Question 6'] = DataFrame1['Question 6'].replace(['B.tech in cs','Bit'], 'Computer Science')
DataFrame1

,Time,Status,Duration (Seconds),IP Address,Country,Region,City / Town / District,Latitude,Longitude,Question 1,...,Question 4,Question 5,Question 6,Question 7,Question 8,Question 9,Question 10,Question 11,Question 12,Question 13
0,10/3/20 5:49 PM,Completed,11646,100.36.167.226,United States,Virginia,Fairfax,-77.2891,38.8209,4.0,...,63,Taiwan,Economics,2021-12-31,Apple/MacBook,Not Working while attending Mason,Some familiarity,Little/none,Some familiarity,NaN
1,10/3/20 5:49 PM,Completed,113,98.169.26.134,United States,Virginia,Fairfax,-77.2630,38.8605,2.0,...,59,India,Finance,2021-05-01,Apple/MacBook,"Working, but not Full Time",Average user,Average user,Little/none,NaN
2,10/3/20 5:49 PM,Completed,572,98.169.52.23,United States,Virginia,Greenway Downs,-77.2331,38.9645,2.0,...,70,India,Computer applications,2022-06-01,Apple/MacBook,"Yes, Full Time",Some familiarity,Little/none,Average user,"As part of my work, I have access to a lot of ..."
3,10/3/20 5:50 PM,Completed,365,69.255.182.253,United States,Virginia,Gainesville,-77.6308,38.8175,2.0,...,66,South korea,Business management,2021-12-31,Microsoft/Windows,Not Working while attending Mason,Average user,Frequent use for projects,Some familiarity,NaN
4,10/3/20 5:51 PM,Completed,92,138.88.108.230,United States,Calculation Failed,Calculation Failed,-97.8220,37.7510,2.0,...,70,USA,Unrecognized Degree,2021-01-01,Apple/MacBook,"Yes, Full Time",Some familiarity,Some familiarity,Average user,Learn
5,10/3/20 5:59 PM,Incomplete,221,108.56.134.80,United States,Virginia,Reston,-77.3489,38.9311,2.0,...,67,India,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,10/3/20 6:23 PM,Completed,115983,108.48.175.220,United States,Virginia,Arlington,-77.0987,38.8600,2.0,...,70,Pakistan,Finance,2022-07-15,Microsoft/Windows,"Working, but not Full Time",Average user,Average user,Average user,To deduce meaningful interpretation for Financ...
7,10/3/20 7:10 PM,Incomplete,40,173.67.199.85,United States,Virginia,Ashburn,-77.5390,39.0180,2.0,...,52,India,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,10/3/20 7:25 PM,Completed,137,74.96.114.12,United States,Virginia,Woodbridge,-77.3197,38.6780,2.0,...,71,China,Economics,2021-12-15,Microsoft/Windows,"Yes, Full Time",Some familiarity,Frequent use for projects,Average user,NaN
9,10/3/20 7:56 PM,Incomplete,179,107.77.241.32,United States,Texas,Calculation Failed,-96.8217,32.7787,4.0,...,71,Uzbekistan,Economics with finance,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,10/3/20 8:14 PM,Completed,127,138.88.182.245,United States,Maryland,Takoma Park,-77.0040,38.9827,2.0,...,66,USA,Computer Science,2022-05-01,Microsoft/Windows,Not Working while attending Mason,Little/none,Little/none,Some familiarity,To see if it is a field I am interested in pur...
11,10/3/20 9:38 PM,Completed,269,72.83.246.60,United States,Virginia,Fairfax,-77.2630,38.8605,4.0,...,66,India,Computer Science and Engineering,2021-05-31,Microsoft/Windows,Not Working while attending Mason,Frequent use for projects,Average user,Frequent use for projects,To learn and explore cutting edge data technol...
12,10/3/20 9:41 PM,Completed,117,96.241.43.105,United States,Virginia,Chantilly,-77.4512,38.9036,2.0,...,69,Romania,Biology,2021-08-26,Apple/MacBook,"Working, but not Full Time",Some familiarity,Average user,Average user,Learn to select the appropriate tools to condu...
13,10/3/20 10:49 PM,Completed,5966,71.191.72.223,United States,Virginia,Burke,-77.2866,38.7851,2.0,...,66,India,Computer Science and Engineering,2021-12-25,Microsoft/Windows,Not Working while attending Mason,Average user,Average user,Average user,NaN
14,10/3/20 11:25 PM,Completed,254,73.134.53.227,United States,Maryland,Hyattsville,-76.8696,38.9544,4.0,...,67,China,Management,2021-12-31,Microsoft/Windows,Not Working while attending Mason,Average user,Little/none,Little/none,improve my skills
15,10/4/20 12:28 AM,Completed,526,73.86.219.52,United States,Maryland,Baltimore,-76.6355,39.3555,4.0,...,72,Uzbekistan,Economics with finance,2022-05-01,Microsoft/Windows,Not Working while attending Mason,Some familiarity,Some familiarity,Some familiarity,My professional goal is to become a Financial ...
16,10/4/20 5:22 AM,Completed,398,69.138.215.127,United States,Virginia,Arlington,-77.1130,38.8747,2.0,...,68,USA,Economics,2022-05-31,Microsoft/WindowsApple/MacBook,"Yes, Full Time",Average user,Some familiarity,Some familiarity,able to compliment my Computational Social Sci...
17,10/4/20 5:36 AM,Completed,128253,72.196.231.70,United States,Virginia,Springfield,-77.2333,38.7438,2.0,...,60,India,Bachelor of Engineering,2021-01-12,Microsoft/Windows,Not Working while attending Mason,Frequent use for projects,Frequent use for projects,Average user,To start a company
18,10/4/20 5:47 AM,Completed,239,100.15.54.17,United States,Virginia,Woodbridge,-77.3197,38.6780,4.0,...,67,Ethiopia,Accounting and isom,2021-12-20,Microsoft/Windows,Not Working while attending Mason,Little/none,Little/none,Average user,To be able understand and manipulate data to m...
19,10/4/20 10:32 AM,Completed,255,184.170.83.239,United States,Virginia,Rustburg,-79.0985,37.2544,4.0,...,67,USA,Statistics,2021-12-20,Apple/MacBook,"Working, but not Full Time",Some familiarity,Fluent/expert,Average user,My ultimate goal is to get a job as a sports a...
20,10/4/20 11:03 AM,Completed,256,100.36.243.102,United States,Virginia,Fairfax,-77.3375,38.8357,4.0,...,74,USA,Computer science,2022-05-01,Microsoft/Windows,"Yes, Full Time",Some familiarity,Some familiarity,Some familiarity,To understand how to properly interpret and di...
21,10/4/20 12:34 PM,Completed,674,108.56.134.80,United States,Virginia,Reston,-77.3489,38.9311,2.0,...,65,India,Computer science,2022-04-16,Microsoft/Windows,Not Working while attending Mason,Some familiarity,Little/none,Average user,"After graduating data analytics, I want myself..."
22,10/4/20 1:36 PM,Completed,130,73.163.163.82,United States,Maryland,Baltimore,-76.5570,39.2784,4.0,...,67,USA,Mathematics & statistics,2021-12-18,Microsoft/WindowsApple/MacBook,"Working, but not Full Time",Some familiarity,Frequent use for projects,Little/none,Learning how to appropriately handle large qua...
23,10/4/20 1:50 PM,Completed,275,138.88.223.87,United States,Calculation Failed,Calculation Failed,-97.8220,37.7510,4.0,...,75,Nigeria,Economics,2021-05-14,Microsoft/Windows,Not Working while attending Mason,Little/none,Little/none,Little/none,To learn and understand the fundamentals and m...
24,10/4/20 9:28 PM,Completed,325,100.36.50.114,United States,Calculation Failed,Calculation Failed,-97.8220,37.7510,4.0,...,67,USA,Systems engineering,2022-12-19,Microsoft/Windows,"Yes, Full Time",Average user,Average user,Average user,The goal is to learn as many programming/stati...
25,10/5/20 9:37 AM,Completed,257,108.51.59.195,United States,Virginia,Burke,-77.2866,38.7851,2.0,...,68,Taiwan,Civil engineering,2021-05-30,Microsoft/Windows,"Yes, Full Time",Average user,Some familiarity,Some familiarity,Learning analytics tool and being good at them
26,10/5/20 9:36 AM,Completed,657,72.83.246.219,United States,Virginia,Fairfax,-77.2630,38.8605,2.0,...,72,India,Bachelor of Engineering,2021-12-11,Apple/MacBook,Not Working while attending Mason,Average user,Frequent use for projects,Average user,I want to be as a data analyst
27,10/5/20 10:36 AM,Completed,1750,100.36.118.186,United States,Virginia,Burke,-77.2866,38.7851,4.0,...,61,Nigeria,Quantity surveying,2023-05-24,Microsoft/Windows,Not Working while attending Mason,Average user,Frequent use for projects,Average user,It is very relevant to my PhD research area an...
28,10/5/20 11:02 AM,Completed,887,172.58.187.98,United States,Maryland,Baltimore,-76.6949,39.2820,4.0,...,64,India,Bachelor of engineering,2021-12-30,Microsoft/Windows,Not Working while attending Mason,Average user,Average user,Average user,Learn how to handle large amount structured an...
29,10/5/20 11:17 AM,Completed,180,72.196.230.201,United States,Virginia,Springfield,-77.2333,38.7438,2.0,...,71,India,Computer Science,2021-12-15,Apple/MacBook,Not Working while attending Mason,Average user,Average user,Frequent use for projects,To become a good Data Analyst and work for top...
30,10/5/20 12:52 PM,Completed,392,108.18.111.204,United States,Virginia,Lorton,-77.2060,38.6911,4.0,...,56,USA,Bs accounting,2021-05-01,Microsoft/Windows,"Yes, Full Time",Little/none,Some familiarity,Some familiarity,Get a better understanding of the granularity ...
31,10/5/20 12:56 PM,Incomplete,192,71.191.72.223,United States,Virginia,Burke,-77.2866,38.7851,2.0,...,70,India,Bachelor of engineering,2021-12-21,Microsoft/WindowsApple/MacBook,Not Working while attending Mason,Average user,Frequent use for projects,Frequent use for projects,NaN
32,10/5/20 1:52 PM,Completed,277,184.191.72.8,United States,Virginia,Falls Church,-77.1425,38.8472,2.0,...,70,United states ; pakistan,Criminology Law and Sociology,2021-12-18,Microsoft/Windows,"Yes, Full Time",Average user,Some familiarity,Some familiarity,Learn how data analytics works
33,10/5/20 3:34 PM,Completed,119,141.156.160.243,United States,Calculation Failed,Calculation Failed,-97.8220,37.7510,4.0,...,73,USA,Economics,2022-05-15,Microsoft/Windows,"Yes, Full Time",Average user,Average user,Average user,Advance my career in data science
34,10/5/20 3:41 PM,Completed,149,71.206.51.121,United States,Maryland,Frederick,-77.2758,39.4624,2.0,...,68,Vietnam,Finance,2022-12-12,Microsoft/Windows,Not Working while attending Mason,Some familiarity,Some familiarity,Some familiarity,Getting a good job
35,10/5/20 5:58 PM,Completed,285,129.174.252.234,United States,Virginia,Fairfax,-77.3375,38.8357,4.0,...,66,Uzbekistan,Psychology,2021-12-20,OtherAcer/Windows,"Yes, Full Time",Some familiarity,Little/none,Little/none,to use the skills at work.

In [48]:
DataFrame1['Question 6'].fillna('No Undergad Degree', inplace=True)
#If you're among the many who don't have a bachelor's but want to get a graduate degree, it is possible. Some universities will 
#take into account your professional experience and certain certificates and/or diplomas you may have. 
#However, it is important for you to do the proper research. (Google)
DataFrame1['Question 7'].fillna(DataFrame1['Question 7'].mode()[0], inplace=True) #Filling it with Mode Values as that is the best estimate we can have
DataFrame1.isnull().sum()
DataFrame1

,Time,Status,Duration (Seconds),IP Address,Country,Region,City / Town / District,Latitude,Longitude,Question 1,...,Question 4,Question 5,Question 6,Question 7,Question 8,Question 9,Question 10,Question 11,Question 12,Question 13
0,10/3/20 5:49 PM,Completed,11646,100.36.167.226,United States,Virginia,Fairfax,-77.2891,38.8209,4.0,...,63,Taiwan,Economics,2021-12-31,Apple/MacBook,Not Working while attending Mason,Some familiarity,Little/none,Some familiarity,NaN
1,10/3/20 5:49 PM,Completed,113,98.169.26.134,United States,Virginia,Fairfax,-77.2630,38.8605,2.0,...,59,India,Finance,2021-05-01,Apple/MacBook,"Working, but not Full Time",Average user,Average user,Little/none,NaN
2,10/3/20 5:49 PM,Completed,572,98.169.52.23,United States,Virginia,Greenway Downs,-77.2331,38.9645,2.0,...,70,India,Computer applications,2022-06-01,Apple/MacBook,"Yes, Full Time",Some familiarity,Little/none,Average user,"As part of my work, I have access to a lot of ..."
3,10/3/20 5:50 PM,Completed,365,69.255.182.253,United States,Virginia,Gainesville,-77.6308,38.8175,2.0,...,66,South korea,Business management,2021-12-31,Microsoft/Windows,Not Working while attending Mason,Average user,Frequent use for projects,Some familiarity,NaN
4,10/3/20 5:51 PM,Completed,92,138.88.108.230,United States,Calculation Failed,Calculation Failed,-97.8220,37.7510,2.0,...,70,USA,Unrecognized Degree,2021-01-01,Apple/MacBook,"Yes, Full Time",Some familiarity,Some familiarity,Average user,Learn
5,10/3/20 5:59 PM,Incomplete,221,108.56.134.80,United States,Virginia,Reston,-77.3489,38.9311,2.0,...,67,India,No Undergad Degree,2021-12-20,NaN,NaN,NaN,NaN,NaN,NaN
6,10/3/20 6:23 PM,Completed,115983,108.48.175.220,United States,Virginia,Arlington,-77.0987,38.8600,2.0,...,70,Pakistan,Finance,2022-07-15,Microsoft/Windows,"Working, but not Full Time",Average user,Average user,Average user,To deduce meaningful interpretation for Financ...
7,10/3/20 7:10 PM,Incomplete,40,173.67.199.85,United States,Virginia,Ashburn,-77.5390,39.0180,2.0,...,52,India,No Undergad Degree,2021-12-20,NaN,NaN,NaN,NaN,NaN,NaN
8,10/3/20 7:25 PM,Completed,137,74.96.114.12,United States,Virginia,Woodbridge,-77.3197,38.6780,2.0,...,71,China,Economics,2021-12-15,Microsoft/Windows,"Yes, Full Time",Some familiarity,Frequent use for projects,Average user,NaN
9,10/3/20 7:56 PM,Incomplete,179,107.77.241.32,United States,Texas,Calculation Failed,-96.8217,32.7787,4.0,...,71,Uzbekistan,Economics with finance,2021-12-20,NaN,NaN,NaN,NaN,NaN,NaN
10,10/3/20 8:14 PM,Completed,127,138.88.182.245,United States,Maryland,Takoma Park,-77.0040,38.9827,2.0,...,66,USA,Computer Science,2022-05-01,Microsoft/Windows,Not Working while attending Mason,Little/none,Little/none,Some familiarity,To see if it is a field I am interested in pur...
11,10/3/20 9:38 PM,Completed,269,72.83.246.60,United States,Virginia,Fairfax,-77.2630,38.8605,4.0,...,66,India,Computer Science and Engineering,2021-05-31,Microsoft/Windows,Not Working while attending Mason,Frequent use for projects,Average user,Frequent use for projects,To learn and explore cutting edge data technol...
12,10/3/20 9:41 PM,Completed,117,96.241.43.105,United States,Virginia,Chantilly,-77.4512,38.9036,2.0,...,69,Romania,Biology,2021-08-26,Apple/MacBook,"Working, but not Full Time",Some familiarity,Average user,Average user,Learn to select the appropriate tools to condu...
13,10/3/20 10:49 PM,Completed,5966,71.191.72.223,United States,Virginia,Burke,-77.2866,38.7851,2.0,...,66,India,Computer Science and Engineering,2021-12-25,Microsoft/Windows,Not Working while attending Mason,Average user,Average user,Average user,NaN
14,10/3/20 11:25 PM,Completed,254,73.134.53.227,United States,Maryland,Hyattsville,-76.8696,38.9544,4.0,...,67,China,Management,2021-12-31,Microsoft/Windows,Not Working while attending Mason,Average user,Little/none,Little/none,improve my skills
15,10/4/20 12:28 AM,Completed,526,73.86.219.52,United States,Maryland,Baltimore,-76.6355,39.3555,4.0,...,72,Uzbekistan,Economics with finance,2022-05-01,Microsoft/Windows,Not Working while attending Mason,Some familiarity,Some familiarity,Some familiarity,My professional goal is to become a Financial ...
16,10/4/20 5:22 AM,Completed,398,69.138.215.127,United States,Virginia,Arlington,-77.1130,38.8747,2.0,...,68,USA,Economics,2022-05-31,Microsoft/WindowsApple/MacBook,"Yes, Full Time",Average user,Some familiarity,Some familiarity,able to compliment my Computational Social Sci...
17,10/4/20 5:36 AM,Completed,128253,72.196.231.70,United States,Virginia,Springfield,-77.2333,38.7438,2.0,...,60,India,Bachelor of Engineering,2021-01-12,Microsoft/Windows,Not Working while attending Mason,Frequent use for projects,Frequent use for projects,Average user,To start a company
18,10/4/20 5:47 AM,Completed,239,100.15.54.17,United States,Virginia,Woodbridge,-77.3197,38.6780,4.0,...,67,Ethiopia,Accounting and isom,2021-12-20,Microsoft/Windows,Not Working while attending Mason,Little/none,Little/none,Average user,To be able understand and manipulate data to m...
19,10/4/20 10:32 AM,Completed,255,184.170.83.239,United States,Virginia,Rustburg,-79.0985,37.2544,4.0,...,67,USA,Statistics,2021-12-20,Apple/MacBook,"Working, but not Full Time",Some familiarity,Fluent/expert,Average user,My ultimate goal is to get a job as a sports a...
20,10/4/20 11:03 AM,Completed,256,100.36.243.102,United States,Virginia,Fairfax,-77.3375,38.8357,4.0,...,74,USA,Computer science,2022-05-01,Microsoft/Windows,"Yes, Full Time",Some familiarity,Some familiarity,Some familiarity,To understand how to properly interpret and di...
21,10/4/20 12:34 PM,Completed,674,108.56.134.80,United States,Virginia,Reston,-77.3489,38.9311,2.0,...,65,India,Computer science,2022-04-16,Microsoft/Windows,Not Working while attending Mason,Some familiarity,Little/none,Average user,"After graduating data analytics, I want myself..."
22,10/4/20 1:36 PM,Completed,130,73.163.163.82,United States,Maryland,Baltimore,-76.5570,39.2784,4.0,...,67,USA,Mathematics & statistics,2021-12-18,Microsoft/WindowsApple/MacBook,"Working, but not Full Time",Some familiarity,Frequent use for projects,Little/none,Learning how to appropriately handle large qua...
23,10/4/20 1:50 PM,Completed,275,138.88.223.87,United States,Calculation Failed,Calculation Failed,-97.8220,37.7510,4.0,...,75,Nigeria,Economics,2021-05-14,Microsoft/Windows,Not Working while attending Mason,Little/none,Little/none,Little/none,To learn and understand the fundamentals and m...
24,10/4/20 9:28 PM,Completed,325,100.36.50.114,United States,Calculation Failed,Calculation Failed,-97.8220,37.7510,4.0,...,67,USA,Systems engineering,2022-12-19,Microsoft/Windows,"Yes, Full Time",Average user,Average user,Average user,The goal is to learn as many programming/stati...
25,10/5/20 9:37 AM,Completed,257,108.51.59.195,United States,Virginia,Burke,-77.2866,38.7851,2.0,...,68,Taiwan,Civil engineering,2021-05-30,Microsoft/Windows,"Yes, Full Time",Average user,Some familiarity,Some familiarity,Learning analytics tool and being good at them
26,10/5/20 9:36 AM,Completed,657,72.83.246.219,United States,Virginia,Fairfax,-77.2630,38.8605,2.0,...,72,India,Bachelor of Engineering,2021-12-11,Apple/MacBook,Not Working while attending Mason,Average user,Frequent use for projects,Average user,I want to be as a data analyst
27,10/5/20 10:36 AM,Completed,1750,100.36.118.186,United States,Virginia,Burke,-77.2866,38.7851,4.0,...,61,Nigeria,Quantity surveying,2023-05-24,Microsoft/Windows,Not Working while attending Mason,Average user,Frequent use for projects,Average user,It is very relevant to my PhD research area an...
28,10/5/20 11:02 AM,Completed,887,172.58.187.98,United States,Maryland,Baltimore,-76.6949,39.2820,4.0,...,64,India,Bachelor of engineering,2021-12-30,Microsoft/Windows,Not Working while attending Mason,Average user,Average user,Average user,Learn how to handle large amount structured an...
29,10/5/20 11:17 AM,Completed,180,72.196.230.201,United States,Virginia,Springfield,-77.2333,38.7438,2.0,...,71,India,Computer Science,2021-12-15,Apple/MacBook,Not Working while attending Mason,Average user,Average user,Frequent use for projects,To become a good Data Analyst and work for top...
30,10/5/20 12:52 PM,Completed,392,108.18.111.204,United States,Virginia,Lorton,-77.2060,38.6911,4.0,...,56,USA,Bs accounting,2021-05-01,Microsoft/Windows,"Yes, Full Time",Little/none,Some familiarity,Some familiarity,Get a better understanding of the granularity ...
31,10/5/20 12:56 PM,Incomplete,192,71.191.72.223,United States,Virginia,Burke,-77.2866,38.7851,2.0,...,70,India,Bachelor of engineering,2021-12-21,Microsoft/WindowsApple/MacBook,Not Working while attending Mason,Average user,Frequent use for projects,Frequent use for projects,NaN
32,10/5/20 1:52 PM,Completed,277,184.191.72.8,United States,Virginia,Falls Church,-77.1425,38.8472,2.0,...,70,United states ; pakistan,Criminology Law and Sociology,2021-12-18,Microsoft/Windows,"Yes, Full Time",Average user,Some familiarity,Some familiarity,Learn how data analytics works
33,10/5/20 3:34 PM,Completed,119,141.156.160.243,United States,Calculation Failed,Calculation Failed,-97.8220,37.7510,4.0,...,73,USA,Economics,2022-05-15,Microsoft/Windows,"Yes, Full Time",Average user,Average user,Average user,Advance my career in data science
34,10/5/20 3:41 PM,Completed,149,71.206.51.121,United States,Maryland,Frederick,-77.2758,39.4624,2.0,...,68,Vietnam,Finance,2022-12-12,Microsoft/Windows,Not Working while attending Mason,Some familiarity,Some familiarity,Some familiarity,Getting a good job
35,10/5/20 5:58 PM,Completed,285,129.174.252.234,United States,Virginia,Fairfax,-77.3375,38.8357,4.0,...,66,Uzbekistan,Psychology,2021-12-20,OtherAcer/Windows,"Yes, Full Time",Some familiarity,Little/none,Little/none,to use the skills at work.

In [51]:
DataFrame1['Question 8'] = DataFrame1['Question 8'].replace('Apple/MacBook', 'Macbook') #Deciding on one spelling
DataFrame1['Question 8'] = DataFrame1['Question 8'].replace('Acer/Windows', 'Windows')
DataFrame1['Question 8'] = DataFrame1['Question 8'].replace('Microsoft/Windows', 'Windows')
DataFrame1['Question 8'] = DataFrame1['Question 8'].replace('Microsoft/WindowsApple/MacBook', 'Windows and Macbook')
DataFrame1['Question 8'].fillna(DataFrame1['Question 8'].mode()[0], inplace=True) #Using Mode as qualitative data does not have a mean or median.
DataFrame1['Question 9'].fillna(DataFrame1['Question 9'].mode()[0], inplace=True) #Using Mode as qualitative data does not have a mean or median.
DataFrame1.head()

,Time,Status,Duration (Seconds),IP Address,Country,Region,City / Town / District,Latitude,Longitude,Question 1,...,Question 4,Question 5,Question 6,Question 7,Question 8,Question 9,Question 10,Question 11,Question 12,Question 13
0,10/3/20 5:49 PM,Completed,11646,100.36.167.226,United States,Virginia,Fairfax,-77.2891,38.8209,4.0,...,63,Taiwan,Economics,2021-12-31,Macbook,Not Working while attending Mason,Some familiarity,Little/none,Some familiarity,NaN
1,10/3/20 5:49 PM,Completed,113,98.169.26.134,United States,Virginia,Fairfax,-77.2630,38.8605,2.0,...,59,India,Finance,2021-05-01,Macbook,"Working, but not Full Time",Average user,Average user,Little/none,NaN
2,10/3/20 5:49 PM,Completed,572,98.169.52.23,United States,Virginia,Greenway Downs,-77.2331,38.9645,2.0,...,70,India,Computer applications,2022-06-01,Macbook,"Yes, Full Time",Some familiarity,Little/none,Average user,"As part of my work, I have access to a lot of ..."
3,10/3/20 5:50 PM,Completed,365,69.255.182.253,United States,Virginia,Gainesville,-77.6308,38.8175,2.0,...,66,South korea,Business management,2021-12-31,Windows,Not Working while attending Mason,Average user,Frequent use for projects,Some familiarity,NaN
4,10/3/20 5:51 PM,Completed,92,138.88.108.230,United States,Calculation Failed,Calculation Failed,-97.8220,37.7510,2.0,...,70,USA,Unrecognized Degree,2021-01-01,Macbook,"Yes, Full Time",Some familiarity,Some familiarity,Average user,Learn

In [56]:
DataFrame1['Question 13'].fillna('No Comments!',inplace=True) #This is forceful i know but there is no other way to interpret this.
DataFrame1.isnull().sum()

Time                      0
Status                    0
Duration (Seconds)        0
IP Address                0
Country                   0
Region                    0
City / Town / District    0
Latitude                  0
Longitude                 0
Question 1                0
Question 2                0
Question 3                0
Question 4                0
Question 5                0
Question 6                0
Question 7                0
Question 8                0
Question 9                0
Question 10               0
Question 11               0
Question 12               0
Question 13               0
dtype: int64

### Exporting CSV File

In [57]:
DataFrame1.to_csv('cleaned_580SurveyCleanup.csv', index=False)

### Q3

In [67]:
DataFrame2 = pd.read_csv('cleaned_580SurveyCleanup.csv')
DataFrame2['Question 1'].describe()

count    36.000000
mean      2.888889
std       1.007905
min       2.000000
25%       2.000000
50%       2.000000
75%       4.000000
max       4.000000
Name: Question 1, dtype: float64

##### This is simple section number and its mean shows that students are more likely or tend to go to section 2.

In [68]:
DataFrame2['Question 2'].describe()

count       36
unique       4
top       Male
freq        18
Name: Question 2, dtype: object

##### We got to know that mode value here is Male

In [69]:
DataFrame2['Question 3'].astype(float).describe()

count    36.000000
mean     27.055556
std       6.484903
min      22.000000
25%      23.000000
50%      25.000000
75%      27.250000
max      55.000000
Name: Question 3, dtype: float64

##### We got to know that mean age is 27 and youngest enrolled student in masters program is 22 (Which could be an anamolay).

In [70]:
DataFrame2['Question 4'].describe()

count    36.000000
mean     67.055556
std       4.863535
min      52.000000
25%      66.000000
50%      67.000000
75%      70.000000
max      75.000000
Name: Question 4, dtype: float64

##### No Anamolies spotted and 67 inches mean height is also plausible

In [71]:
DataFrame2['Question 5'].describe()

count        36
unique       15
top       India
freq         11
Name: Question 5, dtype: object

##### Most Students have cityzenship of India

In [72]:
DataFrame2['Question 6'].describe()

count            36
unique           25
top       Economics
freq              5
Name: Question 6, dtype: object

##### Most Students have a background in Economics

In [73]:
DataFrame2['Question 7'].describe()

count             36
unique            24
top       2021-12-20
freq               6
Name: Question 7, dtype: object

##### The Most repeated date of graduation (expected) is 20-12-2021, however this is most likely an anamoly caused by our forceful population of NAN values with mode

In [74]:
DataFrame2['Question 8'].describe()

count          36
unique          4
top       Windows
freq           24
Name: Question 8, dtype: object

##### Most Students use Windows Based Laptop

In [75]:
DataFrame2['Question 9'].describe()

count                                    36
unique                                    3
top       Not Working while attending Mason
freq                                     20
Name: Question 9, dtype: object

##### Most Students are not working while attending Mason Program. And That is more than half of the class.

In [76]:
DataFrame2['Question 10'].describe()

count               36
unique               4
top       Average user
freq                15
Name: Question 10, dtype: object

In [77]:
DataFrame2['Question 11'].describe()

count              36
unique              5
top       Little/none
freq               11
Name: Question 11, dtype: object

In [78]:
DataFrame2['Question 12'].describe()

count               36
unique               4
top       Average user
freq                15
Name: Question 12, dtype: object

##### Most Students are Average User in Python and SQL (Which are relatively older than R) which is probably why students lack experience in it

In [79]:
DataFrame2['Question 13'].describe()

count               36
unique              28
top       No Comments!
freq                 9
Name: Question 13, dtype: object

##### Statistical Summary here is pretty much useless except for the count. We know that 9 people did not fill out the final question, and that is a huge number. Perhaps this is a good measure that surveys should be short and quick to fill and should not contain subjective questions. We can also infer that they have no goals at all as of now with regards to Data Analytics.